# **Assignment For Numpy**

Difficulty Level **Beginner**

1. Import the numpy package under the name np

In [1]:
import numpy as np


2. Create a null vector of size 10 

In [258]:
import numpy as np
np.zeros((10))



array([0., 0., 0., 0., 0., 0., 0., 0., 0., 0.])

3. Create a vector with values ranging from 10 to 49

In [224]:
x = np.arange(10,50)
x

array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

4. Find the shape of previous array in question 3

In [4]:
np.shape(x)

(40,)

5. Print the type of the previous array in question 3

In [5]:
x.dtype

dtype('int32')

6. Print the numpy version and the configuration


In [252]:
print(np.__version__)
print(np.show_config())


1.18.1
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/hina/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/hina/anaconda3\\Library\\include']
blas_opt_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/hina/anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\li

7. Print the dimension of the array in question 3


In [7]:
np.ndim(x)

1

8. Create a boolean array with all the True values

In [8]:
y = np.arange(10)
z = y < 11
z

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True])

9. Create a two dimensional array




In [9]:
a = np.arange(10,50).reshape(5,8)
a

array([[10, 11, 12, 13, 14, 15, 16, 17],
       [18, 19, 20, 21, 22, 23, 24, 25],
       [26, 27, 28, 29, 30, 31, 32, 33],
       [34, 35, 36, 37, 38, 39, 40, 41],
       [42, 43, 44, 45, 46, 47, 48, 49]])

10. Create a three dimensional array



In [10]:
b = np.arange(10,50).reshape(2,5,4)
b
b = np.arange(10,50).reshape(5,2,4)
b

array([[[10, 11, 12, 13],
        [14, 15, 16, 17]],

       [[18, 19, 20, 21],
        [22, 23, 24, 25]],

       [[26, 27, 28, 29],
        [30, 31, 32, 33]],

       [[34, 35, 36, 37],
        [38, 39, 40, 41]],

       [[42, 43, 44, 45],
        [46, 47, 48, 49]]])

Difficulty Level **Easy**

11. Reverse a vector (first element becomes last)

In [11]:
import numpy as np
n = np.arange(10)
n =  n[::-1]
n

array([9, 8, 7, 6, 5, 4, 3, 2, 1, 0])

12.Create a null vector of size 10 but the fifth value which is 1 

In [21]:
x = np.zeros((10))
x[4] = 1
x

array([0., 0., 0., 0., 1., 0., 0., 0., 0., 0.])

13. Create a 3x3 identity matrix

In [23]:
x = np.zeros((3,3))
x[[0,1,2],[0,1,2]] = 1
print(x)
x = np.identity(3,dtype=int)
print(x)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1 0 0]
 [0 1 0]
 [0 0 1]]


14. arr = np.array([1, 2, 3, 4, 5]) 

---

 Convert the data type of the given array from int to float 

In [24]:
arr = np.array([1, 2, 3, 4, 5])
arr = arr.astype(dtype=float)
arr

array([1., 2., 3., 4., 5.])

15. arr1 =          np.array([[1., 2., 3.],

                    [4., 5., 6.]])  
                      
    arr2 = np.array([[0., 4., 1.],
     
                   [7., 2., 12.]])

---


Multiply arr1 with arr2


In [25]:
arr1 = np.array([[1., 2., 3.], [4., 5., 6.]])
arr2 = np.array([[0., 4., 1.], [7., 2., 12.]])
arr1  * arr2

array([[ 0.,  8.,  3.],
       [28., 10., 72.]])

16. arr1 = np.array([[1., 2., 3.],
                    [4., 5., 6.]]) 
                    
    arr2 = np.array([[0., 4., 1.], 
                    [7., 2., 12.]])


---

Make an array by comparing both the arrays provided above

In [227]:
arr1 = np.array([[1., 2., 3.],
                [4., 5., 6.]]) 
                    
arr2 = np.array([[0., 4., 1.], 
                [7., 2., 12.]]
x = arr1 == arr2
print(x)
y = arr1 < arr2
print(y)
z = arr1 > arr2
print(z)

[[False False False]
 [False False False]]
[[False  True False]
 [ True False  True]]
[[ True False  True]
 [False  True False]]


17. Extract all odd numbers from arr with values(0-9)

In [31]:
arr = np.arange(10)
x = arr[1::2]
print(x)
x = np.arange(1,10,2)
print(x)

[1 3 5 7 9]
[1 3 5 7 9]


18. Replace all odd numbers to -1 from previous array

In [32]:
arr = np.arange(10)
arr[1::2] = -1
arr    



array([ 0, -1,  2, -1,  4, -1,  6, -1,  8, -1])

19. arr = np.arange(10)


---

Replace the values of indexes 5,6,7 and 8 to **12**

In [33]:
arr = np.arange(10)
arr[5:9] = 12
arr

array([ 0,  1,  2,  3,  4, 12, 12, 12, 12,  9])

20. Create a 2d array with 1 on the border and 0 inside

In [34]:
x = np.ones((5,5))
x[1:-1,1:-1] = 0
x


array([[1., 1., 1., 1., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 0., 0., 0., 1.],
       [1., 1., 1., 1., 1.]])

Difficulty Level **Medium**

21. arr2d = np.array([[1, 2, 3],

                    [4, 5, 6], 

                    [7, 8, 9]])

---

Replace the value 5 to 12

In [35]:
arr2d = np.array([[1, 2, 3], [4, 5, 6], [7, 8,9]])
arr2d[1:2,1:2] = 12
arr2d

array([[ 1,  2,  3],
       [ 4, 12,  6],
       [ 7,  8,  9]])

In [ ]:
22. arr3d = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8 ,9],[10,11,12]]])

convert all the values of 1st array to 64

In [36]:
arr3d = np.array([[[1, 2, 3], [4, 5, 6]],[[7, 8 ,9],[10,11,12]]])
arr3d[0] = 64
arr3d

array([[[64, 64, 64],
        [64, 64, 64]],

       [[ 7,  8,  9],
        [10, 11, 12]]])

23. Make a 2-Dimensional array with values 0-9 and slice out the first value from 1st 1-D array from it

In [38]:
x = np.arange(10).reshape((2,5))
print(x)
x[0,0]

[[0 1 2 3 4]
 [5 6 7 8 9]]


0

24. Make a 2-Dimensional array with values 0-9 and slice out the 2nd value from 2nd 1-D array from it

In [39]:
x = np.arange(10).reshape((2,5))
print(x)
print(x[1,1])


[[0 1 2 3 4]
 [5 6 7 8 9]]
6


25. Make a 2-Dimensional array with values 0-9 and slice out the third column but only the first two rows

In [15]:
x = np.random.randint(10,size=(5,8))
print(x)
x[0:2,2:3]

[[7 6 3 2 5 2 5 6]
 [9 3 1 6 8 0 6 6]
 [1 0 5 5 4 6 7 2]
 [3 6 1 0 2 4 9 8]
 [1 2 9 0 8 8 7 2]]


array([[3],
       [1]])

26. Create a 10x10 array with random values and find the minimum and maximum values 

In [40]:
import numpy as np
x = np.random.randint(100,size=(10,10))
min_val = print(np.min(x))
max_val = print(np.max(x))
print(x)
print(np.ndim(x))

1
99
[[52 95 29 87 54 11  4 93 57 85]
 [88  6 59 78 81 17 71  1 41 81]
 [44 36 82 94 95 59 40 96 99 12]
 [22 36 20  9 95 17 19  4 15 72]
 [34 83 62  6 59 69 46 25 28 74]
 [69 94 32 45 38 14 56 92 62 14]
 [20  7 90 82 22 68 39 90 40 60]
 [46 23 14 47 43 68 69 15 90  2]
 [80 60 99 89 64 95  7 42 14 40]
 [ 2 17 10 56 29 78  8 31 55 85]]
2


27. a = np.array([1,2,3,2,3,4,3,4,5,6]) b = np.array([7,2,10,2,7,4,9,4,9,8])
---
Find the common items between a and b


In [4]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
print(np.intersect1d(a,b))


[2 4]


28. a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])

---
Find the positions where elements of a and b match



In [211]:
import numpy as np
a = np.array([1,2,3,2,3,4,3,4,5,6])
b = np.array([7,2,10,2,7,4,9,4,9,8])
np.where(a==b)

(array([1, 3, 5, 7], dtype=int64),)

29.  names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])  data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will**


In [63]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(names)
print(data)
data[names != "Will"]

['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[-0.01119296  0.78917641 -1.18532682  0.89583386]
 [-0.94770153  0.7288813   0.16714783 -0.22076536]
 [-1.19154956 -2.57004312 -0.24233107 -0.61316957]
 [-1.35137291 -0.43401683  0.6172669  -0.21736119]
 [-0.59207061 -1.39717344 -0.96878901 -0.76788654]
 [-0.21103265  0.43501265 -0.88905719 -0.67874736]
 [ 0.78236194 -1.47620053 -1.81042249 -0.46269622]]


array([[-0.01119296,  0.78917641, -1.18532682,  0.89583386],
       [-0.94770153,  0.7288813 ,  0.16714783, -0.22076536],
       [-1.35137291, -0.43401683,  0.6172669 , -0.21736119],
       [-0.21103265,  0.43501265, -0.88905719, -0.67874736],
       [ 0.78236194, -1.47620053, -1.81042249, -0.46269622]])

30. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe']) data = np.random.randn(7, 4)

---
Find all the values from array **data** where the values from array **names** are not equal to **Will** and **Joe**



In [67]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
data = np.random.randn(7, 4)
print(names)
print(data)
data[names == "Bob"]


['Bob' 'Joe' 'Will' 'Bob' 'Will' 'Joe' 'Joe']
[[ 0.83639383 -0.39839192 -0.87274723 -0.13652682]
 [-1.00573233 -0.57187012 -1.31616395  1.3422573 ]
 [-0.89674025 -0.2703501  -2.12600439  0.13360055]
 [-1.35661249 -0.87753596  0.93646669  0.56937758]
 [-1.82512976  0.70719536 -0.8149064   0.67308849]
 [-0.26005755  1.07188741  0.79184598  1.22309635]
 [-0.09428357 -0.89777532 -0.53803     2.349779  ]]


array([[ 0.83639383, -0.39839192, -0.87274723, -0.13652682],
       [-1.35661249, -0.87753596,  0.93646669,  0.56937758]])

Difficulty Level **Hard**

31. Create a 2D array of shape 5x3 to contain decimal numbers between 1 and 15.

In [257]:
x = np.random.uniform(1,15,(5,3))
x

array([[ 2.52954604,  2.63422199,  3.52264394],
       [ 5.72300016,  9.80469167,  5.57771601],
       [ 6.45516073,  4.09675345,  2.38785222],
       [ 9.87598673, 11.77937354,  8.89457503],
       [ 8.79651423,  3.29514758,  3.34788702]])

32. Create an array of shape (2, 2, 4) with decimal numbers between 1 to 16.

In [271]:
x = np.random.uniform(1,16,(2,2,4))
print(x)
print(x.shape)

[[[ 3.83260842 10.94389633  1.67108846  4.40921994]
  [12.45314552  6.35041304  8.54304081  1.46773557]]

 [[13.69334676 10.8817252   3.78238139  8.73947705]
  [11.27141108 12.17726213  4.07832831  2.12997833]]]
(2, 2, 4)


33. Swap axes of the array you created in Question 32

In [272]:
print(x)
y = x.T
print(y)
print(y.shape)


[[[ 3.83260842 10.94389633  1.67108846  4.40921994]
  [12.45314552  6.35041304  8.54304081  1.46773557]]

 [[13.69334676 10.8817252   3.78238139  8.73947705]
  [11.27141108 12.17726213  4.07832831  2.12997833]]]
[[[ 3.83260842 13.69334676]
  [12.45314552 11.27141108]]

 [[10.94389633 10.8817252 ]
  [ 6.35041304 12.17726213]]

 [[ 1.67108846  3.78238139]
  [ 8.54304081  4.07832831]]

 [[ 4.40921994  8.73947705]
  [ 1.46773557  2.12997833]]]
(4, 2, 2)


34. Create an array of size 10, and find the square root of every element in the array, if the values less than 0.5, replace them with 0

In [169]:
x = np.arange(0,1,0.1)
print(x)
size = np.size(x)
print(size)
sqrt = np.sqrt(x)
print(sqrt)
after_replacing = np.where(x<0.5,0,x)
print(after_replacing)

[0.  0.1 0.2 0.3 0.4 0.5 0.6 0.7 0.8 0.9]
10
[0.         0.31622777 0.4472136  0.54772256 0.63245553 0.70710678
 0.77459667 0.83666003 0.89442719 0.9486833 ]
[0.  0.  0.  0.  0.  0.5 0.6 0.7 0.8 0.9]


35. Create two random arrays of range 12 and make an array with the maximum values between each element of the two arrays

In [173]:
x = np.random.randint(12,24,size=(12))
print(x)
y = np.random.randint(16,28,size=(12))
print(y)
np.maximum(x,y)


[16 12 12 21 19 17 18 23 23 18 16 16]
[23 22 22 26 16 24 23 26 21 19 24 17]


array([23, 22, 22, 26, 19, 24, 23, 26, 23, 19, 24, 17])

36. names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])

---
Find the unique names and sort them out!


In [183]:
names = np.array(['Bob', 'Joe', 'Will', 'Bob', 'Will', 'Joe', 'Joe'])
x = np.unique(names)
print(x)
names.sort()
names


['Bob' 'Joe' 'Will']


array(['Bob', 'Bob', 'Joe', 'Joe', 'Joe', 'Will', 'Will'], dtype='<U4')

37. a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])

---
From array a remove all items present in array b




In [210]:
a = np.array([1,2,3,4,5])
b = np.array([5,6,7,8,9])
a = np.setdiff1d(a,b)
print(a)

[1 2 3 4]


38.  Following is the input NumPy array delete column two and insert following new column in its place.

---
sampleArray = numpy.array([[34,43,73],[82,22,12],[53,94,66]]) 


---

newColumn = numpy.array([[10,10,10]])


In [201]:
sampleArray = np.array([[34,43,73],
                        [82,22,12],
                        [53,94,66]])
newColumn = np.array([[10,10,10]])
np.where(sampleArray == sampleArray[0: , 1:2],newColumn,sampleArray)

array([[34, 10, 73],
       [82, 10, 12],
       [53, 10, 66]])

39. x = np.array([[1., 2., 3.], [4., 5., 6.]]) y = np.array([[6., 23.], [-1, 7], [8, 9]])


---
Find the dot product of the above two matrix


In [202]:
x = np.array([[1., 2., 3.], [4., 5., 6.]])
y = np.array([[6., 23.], [-1, 7], [8, 9]])
x.dot(y)

array([[ 28.,  64.],
       [ 67., 181.]])

40. Generate a matrix of 20 random values and find its cumulative sum

In [204]:
x = np.random.randint(1,20,size=(4,5))
print(x)
y = x.cumsum()
print(y)

[[15  9 17  8 10]
 [11  3 18  8 15]
 [ 4 12  5  6  1]
 [10 12  2 15 15]]
[ 15  24  41  49  59  70  73  91  99 114 118 130 135 141 142 152 164 166
 181 196]
